# Generated by Django 5.0.6 on 2024-05-10 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0003_country_broker_currency_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buy',
            name='action',
        ),
        migrations.RemoveField(
            model_name='broker',
            name='country',
        ),
        migrations.RemoveField(
            model_name='buy',
            name='user',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='country',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='country',
        ),
        migrations.DeleteModel(
            name='action',
        ),
        migrations.DeleteModel(
            name='broker',
        ),
        migrations.DeleteModel(
            name='buy',
        ),
        migrations.DeleteModel(
            name='currency',
        ),
        migrations.DeleteModel(
            name='country',
        ),
        migrations.DeleteModel(
            name='manager',
        ),
    ]
