# Generated by Django 5.0.6 on 2024-05-10 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0008_alter_user_actions_alter_user_saldo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='actions',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='saldo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
